input(37)
input('your mom')
name=input('Please give your name: ')
print(name)
k=2
print('with k =', k, 'we get', k**5)
print(f'{20/7: .3g}')
print(f'{20/7: .3f}')
t=(5,-4,7)
print(f'first two elements: {t[0]} {t[1]}')